-- AlterTable
ALTER TABLE `match` MODIFY `duration` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `playerstats` ADD COLUMN `boostUsed` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `demos` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `longestStreak` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `playerId` VARCHAR(191) NOT NULL DEFAULT '';
